
export const TRANSACTION_ROLES = [
  { chartOfAccountId: "", "role": "Mal Alış" },
  { chartOfAccountId: "", "role": "Perakende Satış" },
  { chartOfAccountId: "", "role": "Alım İadesi" },
  { chartOfAccountId: "", "role": "Mal Alış KDV" },
  { chartOfAccountId: "", "role": "Mal Alış İade KDV" },
  { chartOfAccountId: "", "role": "Mal Satış İade KDV" },
  { chartOfAccountId: "", "role": "Mal Satış İndirimi" },
  { chartOfAccountId: "", "role": "Mal Alış Tevkifat" },
  { chartOfAccountId: "", "role": "Mal Satış KDV" },
  { chartOfAccountId: "", "role": "Konsinye Çıkıştan İade Alımı" },
  { chartOfAccountId: "", "role": "Perakende Satış İadesi" },
  { chartOfAccountId: "", "role": "Toptan Satış İadesi" },
  { chartOfAccountId: "", "role": "Teşvikli İthalat" },
  { chartOfAccountId: "", "role": "Teşviksiz İthalat" },
  { chartOfAccountId: "", "role": "İmalattan Giriş" },
  { chartOfAccountId: "", "role": "Sayım Farkı Girişi" },
  { chartOfAccountId: "", "role": "Diğer Girişler" },
  { chartOfAccountId: "", "role": "Teşvikli İhracat İadesi" },
  { chartOfAccountId: "", "role": "Teşviksiz İhracat İadesi" },
  { chartOfAccountId: "", "role": "Diğer Çıkış İadesi" },
  { chartOfAccountId: "", "role": "Fason Giriş" },
  { chartOfAccountId: "", "role": "Fason Çıkış İadesi" },
  { chartOfAccountId: "", "role": "Toptan Satış" },
  { chartOfAccountId: "", "role": "Konsinye Çıkış" },
  { chartOfAccountId: "", "role": "Teşvikli İhracat" },
  { chartOfAccountId: "", "role": "Teşviksiz İhracat" },
  { chartOfAccountId: "", "role": "Üretime Çıkış" },
  { chartOfAccountId: "", "role": "Mamul/Yarı Mamul, Hurda, Fire" },
  { chartOfAccountId: "", "role": "Hammadde, Hurda, Fire Çıkışı" },
  { chartOfAccountId: "", "role": "Dahili Kullanım" },
  { chartOfAccountId: "", "role": "Sayım Farkı Çıkışı" },
  { chartOfAccountId: "", "role": "Diğer Çıkışlar" },
  { chartOfAccountId: "", "role": "Teşvikli İthalat İadesi" },
  { chartOfAccountId: "", "role": "Teşviksiz İthalat İadesi" },
  { chartOfAccountId: "", "role": "Fason Giriş İadesi" },
  { chartOfAccountId: "", "role": "Fason Çıkış" },
  { chartOfAccountId: "", "role": "Bedelsiz Mal Alış İndirimi" },
  { chartOfAccountId: "", "role": "Bedelsiz Mal Satış İndirimi" },
  { chartOfAccountId: "", "role": "Mal Alış İndirimi" },
  { chartOfAccountId: "", "role": "Satılan Malın Maliyeti Hesabı" },
  { chartOfAccountId: "", "role": "Enflasyon Düzeltme Farkı" },
  { chartOfAccountId: "", "role": "Enflasyon Düzeltme Hesabı" },
  { chartOfAccountId: "", "role": "Satılan Malın Maliyet Farkı Hesabı" },
  { chartOfAccountId: "", "role": "Üretim Maliyet Yansıtma Hesabı" },
  { chartOfAccountId: "", "role": "Mal Satış Tevkifat" },
  { chartOfAccountId: "", "role": "Mal Alış İade Tevkifat" },
  { chartOfAccountId: "", "role": "Mal Satış İade Tevkifat" },
  { chartOfAccountId: "", "role": "Mal Alış Tevkifat Karşı Hes." },
  { chartOfAccountId: "", "role": "Mal Satış Tevkifat Karşı Hes." },
  { chartOfAccountId: "", "role": "Mal Alış İade Tevk. Karşı Hes." },
  { chartOfAccountId: "", "role": "Mal Satış İade Tevk. Karşı Hes." },
  { chartOfAccountId: "", "role": "Mamül Malzeme Maliyet Hes." },
  { chartOfAccountId: "", "role": "Mamül Tezgah Maliyet Hes." },
  { chartOfAccountId: "", "role": "Mamül Ek Maliyet Hes." },
  { chartOfAccountId: "", "role": "Genel Mamül Maliyet Hes." },
  { chartOfAccountId: "", "role": "İhraç Kayıtlı Sat. İade Hes." },
  { chartOfAccountId: "", "role": "İhracat Kayıtlı Alış İade Hesabı" },
  { chartOfAccountId: "", "role": "İhracat Kay. Sat. Ert. Kdv Hes." },
  { chartOfAccountId: "", "role": "İhracat Kay. Sat. Ert. Kdv İade Hes." },
  { chartOfAccountId: "", "role": "İhracat Satış Kdv Hesabı" },
  { chartOfAccountId: "", "role": "İhracat Kay. Satış İade Kdv Hes." },
  { chartOfAccountId: "", "role": "Verilen Fiyat Farkı (-)" },
  { chartOfAccountId: "", "role": "Bedelsiz Mal Alış İade İndirimi" },
  { chartOfAccountId: "", "role": "Bedelsiz Mal Satış İade İndirimi" },
  { chartOfAccountId: "", "role": "Cari Evaliasyon" },
  { chartOfAccountId: "", "role": "Cari Evaliasyon Karı" },
  { chartOfAccountId: "", "role": "Cari Evaliasyon Zararı" },
  { chartOfAccountId: "", "role": "Konsinye Çıkıştan İade Alımı" },
  { chartOfAccountId: "", "role": "İhraç Kayıtlı Satış Hesabı Hs." },
  { chartOfAccountId: "", "role": "Alış Faturası" },
  { chartOfAccountId: "", "role": "Alış İade Faturası" },
  { chartOfAccountId: "", "role": "Satış Faturası" },
  { chartOfAccountId: "", "role": "Satış İade Faturası" },
  { chartOfAccountId: "", "role": "Yük. Al.Fat. Yuvarlamaları" },
  { chartOfAccountId: "", "role": "As. Sat.Fat KDV Yuvarlamaları" },
  { chartOfAccountId: "", "role": "Verilen Fiyat Farkı (:)" },
  { chartOfAccountId: "", "role": "Genel Virman Cari" },
  { chartOfAccountId: "", "role": "Nakit Tahsilat" },
  { chartOfAccountId: "", "role": "Al.Tem.Mek (Limit İçi, Geçici)" },
  { chartOfAccountId: "", "role": "Al.Tem.Mek (Limit İçi, Kesin)" },
  { chartOfAccountId: "", "role": "Al.Tem.Mek (Limit İçi, Avans)" },
  { chartOfAccountId: "", "role": "Al.Tem.Mek (Limit Dışı, Geçici)" },
  { chartOfAccountId: "", "role": "Al.Tem.Mek (Limit Dışı, Avans)" },
  { chartOfAccountId: "", "role": "Al.Tem.Mek (İade)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (Limit İçi, Geçici)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (Limit İçi, Kesin)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (Limit İçi, Avans)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (Limit Dışı, Geçici)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (Limit Dışı, Kesin)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (Limit Dışı, Avans)" },
  { chartOfAccountId: "", "role": "V.Tem.Mek (İade)" },
  { chartOfAccountId: "", "role": "Diğer Alış Faturası (Açık)" },
  { chartOfAccountId: "", "role": "Diğer Alış Faturası İade (Açık)" },
  { chartOfAccountId: "", "role": "Havale Alma" },
  { chartOfAccountId: "", "role": "Nakit Ödeme" },
  { chartOfAccountId: "", "role": "Havale Gönderme" },
  { chartOfAccountId: "", "role": "Cari Virman" },
  { chartOfAccountId: "", "role": "Cari Borç Dekontu" },
  { chartOfAccountId: "", "role": "Cari Alacak Dekontu" },
  { chartOfAccountId: "", "role": "AÇ - Portföyde" },
  { chartOfAccountId: "", "role": "AÇ - İade Edildi" },
  { chartOfAccountId: "", "role": "AÇ - Ciro Edildi" },
  { chartOfAccountId: "", "role": "AÇ - İcraya Verildi" },
  { chartOfAccountId: "", "role": "AÇ - Masraf (Kasadan Ödendi)" },
  { chartOfAccountId: "", "role": "AÇ - Masraf (Bankadan Ödendi)" },
  { chartOfAccountId: "", "role": "VÇ - Yeni Verilen" },
  { chartOfAccountId: "", "role": "VÇ - İade Edildi" },
  { chartOfAccountId: "", "role": "VÇ - Masraf (Kasadan Ödendi)" },
  { chartOfAccountId: "", "role": "VÇ - Masraf (Bankadan Ödendi)" },
  { chartOfAccountId: "", "role": "AS - Portföyde" },
  { chartOfAccountId: "", "role": "AS - İade Edildi" },
  { chartOfAccountId: "", "role": "AS - Ciro Edildi" },
  { chartOfAccountId: "", "role": "AS - İcraya Verildi" },
  { chartOfAccountId: "", "role": "AS - Masraf (Kasadan Ödendi)" },
  { chartOfAccountId: "", "role": "AS - Masraf (Bankadan Ödendi)" },
  { chartOfAccountId: "", "role": "BS - Yeni Verilen" },
  { chartOfAccountId: "", "role": "BS - İade Edildi" },
  { chartOfAccountId: "", "role": "BS - Masraf (Kasadan Ödendi)" },
  { chartOfAccountId: "", "role": "Konsinye Giriş" },
  { chartOfAccountId: "", "role": "Konsinye Giriş İadesi" },
  { chartOfAccountId: "", "role": "İhraç Kayıtlı Satış Hesabı" },
  { chartOfAccountId: "", "role": "Alınan Fiyat Farkı (+)" },
  { chartOfAccountId: "", "role": "İhraç Kayıtlı Alış Hesabı" },
  { chartOfAccountId: "", "role": "Verilen Fiyat Farkı (+)" },
  { chartOfAccountId: "", "role": "Alınan Fiyat Farkı (-)" },
  { chartOfAccountId: "", "role": "Depo Transferi (giriş)" },
  { chartOfAccountId: "", "role": "Depo Transferi (çıkış)" }
]





